[[main]]
    # Top-level menu entry
    identifier = "work"
    name = "Work"
    url = "/projects/"
    weight = 1

[[main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    parent = "work"
    weight = 1

[[main]]
    # Top-level menu entry
    identifier = "writing"
    name = "Writing"
    url = "/posts/"
    weight = 2

[[main]]
    identifier = "posts"
    name = "All Posts"
    url = "/posts/"
    parent = "writing"
    weight = 2

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    parent = "writing"
    weight = 3

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    parent = "writing"
    weight = 4

[[main]]
    identifier = "series"
    name = "Series"
    url = "/series/"
    parent = "writing"
    weight = 5

[[main]]
    identifier = "project-type"
    name = "Project Types"
    url = "/project-types/"
    parent = "writing"
    weight = 6

[[main]]
    # Top-level menu entry
    identifier = "About"
    name = "About"
    url = "/about/"
    weight = 7

[[main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    parent = "About"
    weight = 7

[[main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    parent = "About"
    weight = 8